[package]
name = "zcash-vote-setup"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
figment = { version = "0.10", features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
shell-words = "1.1.0"
toml_edit = "0.23.7"
sqlx = {version = "0.8", features = ["runtime-tokio", "sqlite", "macros", "migrate"]}

tokio = { version = "^1.6", features = ["macros", "rt-multi-thread"] }
tonic = {version = "0.13.0", features = ["tls-webpki-roots"]}
prost = "0.13.5"
users = "0.11.0"
clap = {version = "4.5", features = ["derive"]}
glob = "0.3"
rustls = "0.23"

[build-dependencies]
tonic-build = "0.13"
