chainid: zcv-nu72
auth: tskey-auth-kJm4YdgEze11CNTRL-2WsLzHim9McwuE3VyRXcLcGeAkYXkG48D
peers:
  - name: n1
    password: 5Ll4mckk
  - name: n2
    password: P6Wfn4vt
datadir: data
workdir: work
port: 9000
