syntax = "proto3";
package vote_setup.rpc;

message AuthReq {
    string password = 1;
}

message TSAuthKey {
    string name = 1;
    string key = 2;
}

message NodeDef {
    string password = 1;
    string id = 2;
    string pubkey = 3;
    string address = 4;
}

message NodeConfig {
    bytes votedb = 1;
    string config = 2;
    string genesis = 3;
    string run = 4;
    uint32 remaining = 5;
}

service VoteServerSetup {
    rpc GetTSAuthKey(AuthReq) returns (TSAuthKey) {}
    rpc PutNodeDef(NodeDef) returns (NodeConfig) {}
}
