FROM tailscale/tailscale:latest

RUN apk add --no-cache bash curl tar python3 py3-pip supervisor
RUN mkdir -p /var/lib/tailscale /var/log/supervisor
RUN curl -fsSL https://github.com/cometbft/cometbft/releases/download/v1.0.1/cometbft_1.0.1_linux_arm64.tar.gz \
    | tar -xz -C /usr/local/bin cometbft

RUN curl -fsSL https://github.com/hhanh00/zcash-vote-server/releases/download/v1.2.1/zcash-vote-server-aarch64.tgz \
    | tar -xz -C /root

COPY Rocket.toml /root/zcash-vote-server/
COPY supervisord.conf /root/
COPY run.sh /root/

ENTRYPOINT ["/bin/bash", "/root/run.sh"]
