[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:tailscaled]
command=/usr/local/bin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock
autostart=true
autorestart=true

[program:cometbft]
command=/bin/bash -c "sleep 5 && /usr/local/bin/cometbft start"
directory=/home/user
autorestart=true
autostart=false
priority=20
environment=HOME=/home/user

[program:zcash-vote-server]
command=/zcash-vote-server/zcash-vote-server
directory=/home/user
autorestart=true
autostart=false
priority=10
environment=HOME=/home/user
